
server {
    listen 80;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index  /app/dist/shop-app/browser/index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Handle 404 errors (for SPA routing)
    error_page 404 /index.html;
}